<a href="https://colab.research.google.com/github/nhosamani/Machine_Learning/blob/main/KNN_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
X = df.iloc[:,[-1]].values
Y = df.iloc[:,-1].values


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.25,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler


In [ ]:
sc=StandardScaler()


In [ ]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [ ]:
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
Y_pred=knn.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report as cr

In [ ]:
cr(Y_test,Y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00       186\n           1       1.00      1.00      1.00       114\n\n    accuracy                           1.00       300\n   macro avg       1.00      1.00      1.00       300\nweighted avg       1.00      1.00      1.00       300\n'

In [ ]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklearn.metrics.pairwise import euclidean_distances,manhattan_distances ,cosine_distances
x=[[1,2],[2,2]]
y=[[2,2],[3,3]]

manhattan_distances(x,y)


array([[1., 3.],
       [0., 2.]])

In [ ]:
euclidean_distances(x,y)

array([[1.        , 2.23606798],
       [0.        , 1.41421356]])

In [ ]:
cosine_distances(x,y)

array([[5.13167019e-02, 5.13167019e-02],
       [2.22044605e-16, 0.00000000e+00]])