<a href="https://colab.research.google.com/github/nhosamani/Machine_Learning/blob/main/Predicting_Employee_Exit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# We will be working on Employee Data. This is employee attrition data. The 'left' named column represents exit from the company or not.
# The data consists of categorical & number data. Thus, needs data preprocessing. Make use of preprocessing techniques that you have learnt & build model to predict 'left' named column



In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv('/content/HR_comma_sep.csv')

In [7]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years    sales  salary  
0                          0    sales     low  
1                          0    sales  medium  
2                          0    sales  medium  
3                          0    sales     low  
4                          0    sales     low  
...                      ...      ...     ...  
14994                      0  support     low  
14995                      0  support     low  
14996                      0  support     low  
14997                      0  support     low  
14998                      0  support     low  

[14999 rows x 10 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   sales                  14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [9]:
df.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

In [10]:
df.corr()

satisfaction_level  last_evaluation  number_project  \
satisfaction_level               1.000000         0.105021       -0.142970   
last_evaluation                  0.105021         1.000000        0.349333   
number_project                  -0.142970         0.349333        1.000000   
average_montly_hours            -0.020048         0.339742        0.417211   
time_spend_company              -0.100866         0.131591        0.196786   
Work_accident                    0.058697        -0.007104       -0.004741   
left                            -0.388375         0.006567        0.023787   
promotion_last_5years            0.025605        -0.008684       -0.006064   

                       average_montly_hours  time_spend_company  \
satisfaction_level                -0.020048           -0.100866   
last_evaluation                    0.339742            0.131591   
number_project                     0.417211            0.196786   
average_montly_hours               1.000000            0.127755   
time_spend_company                 0.127755            1.000000   
Work_accident                     -0.010143            0.002120   
left                               0.071287            0.144822   
promotion_last_5years             -0.003544            0.067433   

                       Work_accident      left  promotion_last_5years  
satisfaction_level          0.058697 -0.388375               0.025605  
last_evaluation            -0.007104  0.006567              -0.008684  
number_project             -0.004741  0.023787              -0.006064  
average_montly_hours       -0.010143  0.071287              -0.003544  
time_spend_company          0.002120  0.144822               0.067433  
Work_accident               1.000000 -0.154622               0.039245  
left                       -0.154622  1.000000              -0.061788  
promotion_last_5years       0.039245 -0.061788               1.000000

In [11]:
df.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'sales', 'salary'],
      dtype='object')

In [12]:
df.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
sales                     object
salary                    object
dtype: object

In [13]:
df['sales'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [14]:
df['salary'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [15]:
# we will consider two cases as of now 
# 1 Converting both Sales and Salary Column into numbers using Data Preprocessing techniques 
# 2 Drop Sales Column and Convert only Salary using Data Preprocessing techniques

In [16]:
# Data preprocessing 
df=pd.get_dummies(data=df,columns=['sales','salary'])

In [17]:
df.shape

(14999, 21)

In [18]:
X=df.drop('left',axis=1).values
X.shape

(14999, 20)

In [19]:
y=df['left'].values
y.shape

(14999,)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [21]:
from sklearn.preprocessing import StandardScaler
Mm=StandardScaler()
X_train=Mm.fit_transform(X_train)
X_test=Mm.transform(X_test)

In [22]:
print(X_train)



[[ 1.2388582   0.95201436 -0.65084987 ... -0.29879847  1.02365967
  -0.86807049]
 [ 1.44056081 -0.86192569  0.15743123 ... -0.29879847 -0.97688717
   1.15198018]
 [ 1.11783663  1.6541847   0.96571232 ... -0.29879847  1.02365967
  -0.86807049]
 ...
 [ 0.31102618  1.30309953  0.96571232 ... -0.29879847 -0.97688717
   1.15198018]
 [ 0.67409089 -0.7448973   0.96571232 ...  3.34673733 -0.97688717
  -0.86807049]
 [-0.21340061 -0.21826955  0.96571232 ... -0.29879847  1.02365967
  -0.86807049]]


In [23]:
print(X_test)

[[-0.69748688 -0.86192569 -1.45913096 ... -0.29879847 -0.97688717
   1.15198018]
 [-0.25374113  1.42012792 -0.65084987 ... -0.29879847 -0.97688717
   1.15198018]
 [ 0.43204775 -0.27678374  0.96571232 ... -0.29879847 -0.97688717
   1.15198018]
 ...
 [ 0.59340984  0.89350016  0.96571232 ... -0.29879847  1.02365967
  -0.86807049]
 [ 0.59340984  1.30309953  0.15743123 ... -0.29879847 -0.97688717
   1.15198018]
 [-0.09237904  0.01578723 -0.65084987 ... -0.29879847 -0.97688717
   1.15198018]]


In [24]:
#KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [25]:
y_pred=knn.predict(X_test)
y_pred

array([1, 0, 0, ..., 1, 1, 0])

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[2735,  146],
       [  76,  793]])

In [27]:
neighbor=np.arange(1,9)
train_acc=np.empty(len(neighbor))
test_acc=np.empty(len(neighbor))

In [28]:
# find the best value of k
for i,j in enumerate(neighbor):
  KernelCenterer=KNeighborsClassifier(n_neighbors=j)
  knn.fit(X_train,y_train)

  train_acc[i]=knn.score(X_train,y_train)
  test_acc[i]=knn.score(X_test,y_test)

In [30]:
train_acc

array([0.9611521, 0.9611521, 0.9611521, 0.9611521, 0.9611521, 0.9611521,
       0.9611521, 0.9611521])

In [31]:
test_acc

array([0.9408, 0.9408, 0.9408, 0.9408, 0.9408, 0.9408, 0.9408, 0.9408])